### ISSUE TITLE
Should we only accept `uuid` for API key

### ISSUE THREAD

**Issue by aaronpowell** [microsoft/azure-openai-service-proxy#115]
I just noticed that we enforce at both a DB and code level that the API key must be a `uuid` https://github.com/microsoft/azure-openai-service-proxy/blob/583bb2f110a8aee1d0595c1e9d40b71d17a0fb04/src/proxy/app/authorize.py#L97

This got me wondering about the "single code" scenario, which #80 saw us remove the DB column and instead the expectation is that there will be a registered attendee whose code is shared.

But in this scenario, you may want to have a more "readable" API key, one that you edit via the admin UI and set for the user, but this won't work because the DB column is a `uuid` and we enforce that in the auth pipeline.

@gloveboxes I think we should explore this a bit more.

**Comment by gloveboxes** [comment]
@aaronpowell i think we could handle think with a short link service like Ms.aka ?

**Comment by aaronpowell** [comment]
What would the aka.ms link direct people to? Currently the playground doesn't accept the API Key via a query string, only entry in the textbox.

Microsoft AI Tour, for example, is using a shared key in their workshops, so we'd need to validate with the team running those if registration would be an acceptable addition to the workshop flow.

**Comment by gloveboxes** [comment]
Done
