### ISSUE TITLE
The 404 when providing an invalid event id is surfaced as a 503

### ISSUE THREAD

**Issue by aaronpowell** [microsoft/azure-openai-service-proxy#122]
If the event id provided to `/api/v1/event/{id}` is invalid it generates a 404: https://github.com/microsoft/azure-openai-service-proxy/blob/c2179ad59e2b03861f51e0283c21fb0a8d1fe46f/src/proxy/app/routes/event_registration.py#L86-L90

Unfortunately, this becomes a 503 as there is a generic exception handler: https://github.com/microsoft/azure-openai-service-proxy/blob/c2179ad59e2b03861f51e0283c21fb0a8d1fe46f/src/proxy/app/routes/event_registration.py#L101-L107

This causes a problem trying to handle errors correctly.

**Comment by gloveboxes** [comment]
fixed
