### ISSUE TITLE
Content filtering exception management fails in the playground on second violation

### ISSUE THREAD

**Issue by gloveboxes** [microsoft/azure-openai-service-proxy#136]
Content filtering exception works in the playground the first time but fails the second time and the playground throws an exception the second time. See video of use case: https://github.com/microsoft/azure-openai-service-proxy/assets/9853509/abc5c361-dac5-4463-8265-7cc17ee429c4

**Comment by aaronpowell** [comment]
Are you still able to reproduce this? I've not been able to

**Comment by gloveboxes** [comment]
fixed
