### ISSUE TITLE
Event admin page start/finish date-time adds offset on saving, editing displayed time

### ISSUE THREAD

**Issue by reneenoble** [microsoft/azure-openai-service-proxy#161]
Whenever you save an event in the admin interface (even if you have made no changes to the event finish time), the event finish date/time will add the offset associated with the selected timezone. 
Eg 04/03/2024 10:59am becomes 03/03/2024 11:59pm, when timezone is set to UTC+10 Sydney time (Sydney is currently on +11 on daylight savings so I think the labelling is also incorrect)

I have replicated on UTC-8 Los Angeles time, seeing the offset subtracted.

https://github.com/microsoft/azure-openai-service-proxy/assets/7269759/aef50796-e7cc-4c87-8b44-5932347c5829

https://github.com/microsoft/azure-openai-service-proxy/assets/7269759/7b4dfadf-9580-4130-87af-27cac768b079

**Comment by gloveboxes** [comment]
fixed
