### ISSUE TITLE
[DOCS] Redirect URIs on Entra App Registration already added

### ISSUE THREAD

**Issue by rajbos** [microsoft/azure-openai-service-proxy#301]
The Redirect URIs configuration for the Entra ID App Registration are already configured for the Administration part after deploying the web app. Looks like this is inserted from the script [here](https://github.com/microsoft/azure-openai-service-proxy/blob/ae43a4ea4b00ddfb469538d23b75380947850955/infra/scripts/setup-app-redirect-uris.sh#L47). That means the docs [here](https://github.com/microsoft/azure-openai-service-proxy/blob/ae43a4ea4b00ddfb469538d23b75380947850955/docs/docs/deployment.md?plain=1#L99) can be updated to reflect this.

**Comment by gloveboxes** [comment]
@rajbos ah interesting, we must have our tenant locked down as it fails for me. I'll amend the docs to say you may need to manual add redirect url. Thanks, Dave
